package net.endertime.enderkomplex.bungee.container;

import java.util.ArrayList;

public class ChatBlacklist {

    public static ArrayList<String> adblacklist = new ArrayList<>();
    public static ArrayList<String> blacklist = new ArrayList<>();
    public static ArrayList<String> whitelist = new ArrayList<>();

    public static void fillArrayList() {
        whitelist.add("shop.endertime.net");
        whitelist.add("ts.endertime.net");
        whitelist.add("endertime.net");
        ///////////////////////////////////////////
        adblacklist.add(".com");
        adblacklist.add(".org");
        adblacklist.add(".net");
        adblacklist.add(".n e t");
        adblacklist.add(". n e t");
        adblacklist.add(". n et");
        adblacklist.add(". ne t");
        adblacklist.add(".n et");
        adblacklist.add(".us");
        adblacklist.add(".co");
        adblacklist.add(".de");
        adblacklist.add(".biz");
        adblacklist.add(".info");
        adblacklist.add(".yt");
        adblacklist.add(".tv");
        adblacklist.add(".xyz");
        adblacklist.add(".fr");
        adblacklist.add(".ch");
        adblacklist.add(".au");
        adblacklist.add(".at");
        adblacklist.add(".in");
        adblacklist.add(".jp");
        adblacklist.add(".nl");
        adblacklist.add(".uk");
        adblacklist.add(".no");
        adblacklist.add(".ru");
        adblacklist.add(".br");
        adblacklist.add(".tk");
        adblacklist.add(".ml");
        adblacklist.add(".ga");
        adblacklist.add(".cf");
        adblacklist.add(".gq");
        adblacklist.add(".ip");
        adblacklist.add(".dee");
        adblacklist.add(".d e");
        adblacklist.add(". d e");
        adblacklist.add(", d e");
        adblacklist.add("[punkt]");
        adblacklist.add("(punkt)");
        adblacklist.add("[.]");
        adblacklist.add("(,)");
        adblacklist.add("(.)");
        adblacklist.add("{,}");
        adblacklist.add("{.}");
        adblacklist.add("http:");
        adblacklist.add("https:");
        adblacklist.add("www");
        ///////////////////////////////////////////
        blacklist.add("anus");
        blacklist.add("b1tch");
        blacklist.add("bastard");
        blacklist.add("biatch");
        blacklist.add("bitch");
        blacklist.add("bitches");
        blacklist.add("blow job");
        blacklist.add("blow");
        blacklist.add("blowjob");
        blacklist.add("c0ck");
        blacklist.add("cock");
        blacklist.add("d1ck");
        blacklist.add("d1ld0");
        blacklist.add("d1ldo");
        blacklist.add("faggit");
        blacklist.add("faggot");
        blacklist.add("fagot");
        blacklist.add("fuck");
        blacklist.add("f-u-c-k");
        blacklist.add("ficken");
        blacklist.add("fick");
        blacklist.add("fuckoff");
        blacklist.add("fucks");
        blacklist.add("fuk");
        blacklist.add("fvck");
        blacklist.add("fxck");
        blacklist.add("schwuchtel");
        blacklist.add("hitler");
        blacklist.add("nigga");
        blacklist.add("niggah");
        blacklist.add("nigger");
        blacklist.add("pedo");
        blacklist.add("penis");
        blacklist.add("fotze");
        blacklist.add("hackfresse");
        blacklist.add("hurensohn");
        blacklist.add("huansohn");
        blacklist.add("huensohn");
        blacklist.add("huso");
        blacklist.add("hure");
        blacklist.add("hirnamputiert");
        blacklist.add("honk");
        blacklist.add("Loser");
        blacklist.add("mongo");
        blacklist.add("pimmel");
        blacklist.add("pimmelfresse");
        blacklist.add("schlampe");
        blacklist.add("spastard");
        blacklist.add("afterlecker");
        blacklist.add("arschficker");
        blacklist.add("arschgeburt");
        blacklist.add("arschgeige");
        blacklist.add("arschgesicht");
        blacklist.add("arschlecker");
        blacklist.add("arschloch");
        blacklist.add("arschlöcher");
        blacklist.add("drecksack");
        blacklist.add("drecksau");
        blacklist.add("drecksfotze");
        blacklist.add("drecksnigger");
        blacklist.add("drecksnutte");
        blacklist.add("dreckspack");
        blacklist.add("dreckvotze");
        blacklist.add("ficker");
        blacklist.add("faggot");
        blacklist.add("fickfehler");
        blacklist.add("fickfresse");
        blacklist.add("fickgesicht");
        blacklist.add("ficknudel");
        blacklist.add("ficksau");
        blacklist.add("hackfresse");
        blacklist.add("lusche");
        blacklist.add("missgeburt");
        blacklist.add("misgeburt");
        blacklist.add("miststück");
        blacklist.add("misset");
        blacklist.add("nazi");
        blacklist.add("nazis");
        blacklist.add("penner");
        blacklist.add("scheisser");
        blacklist.add("sieg heil");
        blacklist.add("vollidiot");
        blacklist.add("volldepp");
        blacklist.add("wichser");
        blacklist.add("wichsvorlage");
        blacklist.add("wixa");
        blacklist.add("wixen");
        blacklist.add("wixer");
        blacklist.add("wixxer");
        blacklist.add("wixxxer");
        blacklist.add("wixxxxer");
        blacklist.add("hdf");
        blacklist.add("fresse");
        blacklist.add("arschloch");
        blacklist.add("arsch");
        blacklist.add("trottel");
        blacklist.add("fucking");
        blacklist.add("verfickt");
        blacklist.add("fuck");
        blacklist.add("negger");
    }

}
